engine
init ( struct(
               "dt", .03 ...
              ,"frames", 600 ...
              ,"agents", 10 ...
              ,"goal", 3 ...
              % ,"walls", ...
              ) )
looptest;
