engine
init ( struct(
               "dt", .05 ...
              ,"frames", 300 ...
              ,"agents", 10 ...
              ,"goal", 3 ...
              % ,"walls", ...
              ) )
looptest;
